# Site info
title: Les Mots Nouveaux
email: lesmotsnouveauxblog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Des mots de tous (?) les jours, pour toutes (?) les occasions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lesmotsnouveaux.com" # the base hostname & protocol for your site

# Personal info
#twitter_username: jekyllrb
github_username:  LesMotsNouveauxBlog
favicon: "/img/favicon.ico"
logo: "/img/logo.png"

# Site settings
default_column: "two"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/blog/page:num/'
permalink: /blog/:title.html

include: ['_pages']
relative_permalinks: false